// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPdVroBBRjMH2xdPD3DL6BmSsidggCVFQ',
    appId: '1:662298370437:web:9d11930905ebc97ae5a4ec',
    messagingSenderId: '662298370437',
    projectId: 'dhanush-893a1',
    authDomain: 'dhanush-893a1.firebaseapp.com',
    storageBucket: 'dhanush-893a1.appspot.com',
    measurementId: 'G-SQ1E3D0CHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTDQ73P0XJlOfuDg3kjdbP2h_BUUFn9sg',
    appId: '1:662298370437:android:374932db262c13cbe5a4ec',
    messagingSenderId: '662298370437',
    projectId: 'dhanush-893a1',
    storageBucket: 'dhanush-893a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBacKHH-8pGodhQ25uPg3hhbgMyx6LFs80',
    appId: '1:662298370437:ios:923fae47d91b0f2be5a4ec',
    messagingSenderId: '662298370437',
    projectId: 'dhanush-893a1',
    storageBucket: 'dhanush-893a1.appspot.com',
    iosBundleId: 'com.example.osapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBacKHH-8pGodhQ25uPg3hhbgMyx6LFs80',
    appId: '1:662298370437:ios:923fae47d91b0f2be5a4ec',
    messagingSenderId: '662298370437',
    projectId: 'dhanush-893a1',
    storageBucket: 'dhanush-893a1.appspot.com',
    iosBundleId: 'com.example.osapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPdVroBBRjMH2xdPD3DL6BmSsidggCVFQ',
    appId: '1:662298370437:web:df0bd567c32d60dbe5a4ec',
    messagingSenderId: '662298370437',
    projectId: 'dhanush-893a1',
    authDomain: 'dhanush-893a1.firebaseapp.com',
    storageBucket: 'dhanush-893a1.appspot.com',
    measurementId: 'G-Q82FGL1MVE',
  );
}
